### ISSUE TITLE
SQL DB Errors

### ISSUE THREAD

**Issue by ghost** [FICTURE7/CoCSharp#102]
I compiled the latest source in VS2017 and it manages to compile with no errors and gets as far as loading into the assetmanager. However, it then breaks and outputs the following to the error.log file:

[17/02/22 - 11:53:08.626][error] - Unable to start IDbManager instance: MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown database 'cocsharp'
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.Serialization.MySqlSession.<ConnectAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at CoCSharp.Server.Db.MySqlDbManager..ctor(IServer server) in C:\Users\marti\Desktop\CoCSharp\src\CoCSharp.Server\Db\MySqlDbManager.cs:line 86
   at CoCSharp.Server.Server.Start() in C:\Users\****\Desktop\CoCSharp\src\CoCSharp.Server\Server.cs:line 166.

I have tried both mysql for windows and xampp and it is the same error on both. There are no warnings in warn.log as well and all of the detail in server_config.xml are all correct for the DB which fully works.

If you need anything else, please tell me.

**Comment by FICTURE7** [comment]
You should run this [script](https://github.com/FICTURE7/CoCSharp/blob/server-dev/src/CoCSharp.Server/contents/cocsharp.mysql) in a MySQL shell.

**Comment by ghost** [comment]
Thanks, it runs now on windows.

**Comment by FICTURE7** [comment]
Great, I guess I can close this now. ^^
