### ISSUE TITLE
Libsodium error. Fixed.

### ISSUE THREAD

**Issue by StavrosNicolaou** [FICTURE7/CoCSharp#103]
Hello. I get this error once someone connects. A fix would be awesome.
.net framework is installed.

When i test it on my pc it works fine.
When i test it on windows vps, that pops-up.

[17/03/06 - 04:22:19.654][error] - Unable to process accept! System.TypeInitializationException: The type initializer for 'Sodium.SodiumCore' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libsodium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DynamicDllInvokeType.sodium_init()
   at Sodium.SodiumCore.Init()
   at Sodium.SodiumCore..cctor()
   --- End of inner exception stack trace ---
   at Sodium.SodiumCore.GetRandomBytes(Int32 count)
   at Sodium.PublicKeyBox.GenerateNonce()
   at CoCSharp.Network.Cryptography.Crypto8.GenerateNonce() in C:\Users\CPS\Desktop\CRSharp-cr-sharp-master\src\CoCSharp\Network\Cryptography\Crypto8.cs:line 342
   at CoCSharp.Logic.Session..ctor() in C:\Users\CPS\Desktop\CRSharp-cr-sharp-master\src\CoCSharp\Logic\Session.cs:line 17
   at CoCSharp.Server.RemoteSession..ctor(IServer server) in C:\Users\CPS\Desktop\CRSharp-cr-sharp-master\src\CoCSharp.Server\RemoteSession.cs:line 10
   at CoCSharp.Server.Client..ctor(Server server, Socket socket) in C:\Users\CPS\Desktop\CRSharp-cr-sharp-master\src\CoCSharp.Server\Client.cs:line 35
   at CoCSharp.Server.Server.ProcessAccept(SocketAsyncEventArgs args) in C:\Users\CPS\Desktop\CRSharp-cr-sharp-master\src\CoCSharp.Server\Server.Listening.cs:line 86

**Comment by JJBreaker** [comment]
Add the libsodium.dll dll in (packages \ libsodium-net.0.9.0 \ output) and Sodium.dll the project references

**Comment by StavrosNicolaou** [comment]
Already added but i replaced. Still not fixed.

**Comment by StavrosNicolaou** [comment]
It's fixed. I installed vs 2015 on vps and it worked (:

**Comment by FICTURE7** [comment]
I don't recommend you to use the current branch, because its broken.

**Comment by StavrosNicolaou** [comment]
im not using current one, I'm using the one with the commit you made on before you broke stuff.
